// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogs: dynamic(() => import("./Blogs")),
  case_studies: dynamic(() => import("./CaseStudies")),
  cta_section: dynamic(() => import("./CtaSection")),
  hero: dynamic(() => import("./Hero")),
  process_time_line: dynamic(() => import("./ProcessTimeLine")),
  resources: dynamic(() => import("./Resources")),
  services: dynamic(() => import("./Services")),
  statistics: dynamic(() => import("./Statistics")),
};
